volumes:
  pgdata:

services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    shm_size: 2g
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --lc-collate=C --lc-ctype=C
#    ports:
#      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - ./postgresql.conf:/etc/postgresql/postgresql.conf
#    command: [ "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s