name: rust_project
services:
  consumer:
    image: rust_project
    pull_policy: never
    restart: unless-stopped
    build: .
    environment: &env
      DB_URL: postgres://postgres:postgres@postgres/postgres
    command: consumer
