volumes:
  mongo_data:
  mongo_config:

services:
  mongo:
    image: mongo:8
    restart: always
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: changepassword
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      - ./conf/mongo-replication.key:/etc/mongo-replication.key
      - ./conf/enabled:/sys/kernel/mm/transparent_hugepage/enabled
    command: [ "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongo-replication.key" ]
    healthcheck:
      test: test $$(mongosh -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet --eval 'try {rs.status().ok} catch (err) {rs.initiate().ok}') -eq 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s