volumes:
  miniodata:

services:
  minio:
    image: quay.io/minio/minio
    restart: always
    volumes:
      - miniodata:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=changepassword
    command: server /data --console-address=:9001

  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./nginx_minio.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/etc/nginx/cert/
