volumes:
  mysqldata:

services:
  mysql:
    image: mysql:8
    restart: always
    shm_size: 2g
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: changepassword
      LANG: C.utf8
      TZ: Asia/Shanghai
#    ports:
#      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s