volumes:
  miniodata:

services:
  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: changepassword
    command: server /data --console-address=:9001
