volumes:
  mongo_data:
  mongo_config:

services:
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      - ./conf/enabled:/sys/kernel/mm/transparent_hugepage/enabled
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: changepassword
    healthcheck:
      test: test $$(mongosh -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet --eval 'db.serverStatus().ok') -eq 1
      interval: 5s
      timeout: 2s
      retries: 30
      start_period: 5s